### ISSUE TITLE
Question: Any insights on how to implement these?

### ISSUE THREAD

**Issue by adam-beck** [clux/decay#4]
I understand these algorithms and how they work, but what I haven't been able to find any information on is how to implement these. For instance Reddit has millions of posts and new ones every second. Do they run this algorithm every (say) minute against each post (past and present) and then sort the database by that? 

Do you have any articles or OS projects that have this implemented on a small scale to give a better idea of how it's done? I could go through Reddit but it's very complex for someone like me at the moment and I just want a basic answer. Yes, I'm being lazy.

**Comment by clux** [comment]
Hey there. Yes, the large scale solutions to this I can unfortunately only speculate. The smaller subset of posts that needs to be continuously updated on a site like reddit would almost certainly require some division of labor and several active post lists that are being continuously updated. This is the harder stuff that you would need to dive into their source for.

At a certain point though, reddit stops updating most the posts by date (because no one browses too far back in the 'hot' view anyway) and allows you to just sort by the sum of votes (top weekly, daily, monthly views etc).  

A safe small-scale starting point is really just updating the last week worth (or some sensible recent cutoff) of posts periodically, like every 1-15minutes depending on your needs. A GET request to see the latest, hot-sorted posts would then just get a subset of paginated posts up to your cutoff (one week say). Older posts would not be available under such a view (because you can't expect to always be able to touch every row in the database every `n` minutes), but such a view will contain the _latest_ stuff.

A slightly modified readme example with some pseudo-database code for reference:

```js
var decay = require('decay');
var hotScore = decay.redditHot();

setInterval(function () {
  var latest = yield db.posts.get({age: 7*24*3600}); // last week of posts
  latest.map((post) => {
    post.score = hotScore(post.upVotes, post.dnVotes, post.date);
    return db.posts.update(post);
  });
}, 1000 * 60 * 5); // run every 5 minutes, say
```

The database code there can be optimized a lot more by moving such a routine more towards the database end, but a basic `setInterval` routine should work fine for starters.

Older `score` entries in the database here would be out of date and inaccurate once their age exceeds one week, but that's fine. You are not showing these posts in this view anyway.

### ---
Hopefully, that was somewhat useful. I haven't inspected any projects using this kind of thing in detail, but a quick [github search](https://github.com/search?l=javascript&q=%22require%28%27decay%27%29%22&ref=searchresults&type=Code&utf8=%E2%9C%93) finds some users are doing it :)

**Comment by clux** [comment]
Going to close this, but if you or anyone else come across other useful resources, feel free to post them here.

**Comment by adam-beck** [comment]
These links may provide more insight for anybody who wants to implement these algorithms:

http://inaka.net/blog/2015/03/25/hot-score-with-ruby-postgresql-and-elastic-part-1/
http://inaka.net/blog/2015/04/01/hot-score-with-ruby-postgresql-and-elastic-part-2/
